### ISSUE TITLE
Add function 'forget my password' on login screen

### ISSUE THREAD

**Issue by BIEMAX** [BIEMAX/financial-manager-app#70]

**Comment by Myrfion** [comment]
Hello, does it only include front-end changes or some back-end stuff?

**Comment by BIEMAX** [comment]
Hello, includes both of them. I need to validade how to send and mail and temporary link to change pass.

**Comment by BIEMAX** [comment]
Already implemented as issue [#396](https://github.com/BIEMAX/as-plus/issues/396)
